name: G-SHOP USA STEALTH BOT
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  ultra-boost:
    runs-on: ubuntu-latest
    steps:
      - name: Injecting USA Traffic
        run: |
          VIDEO_ID="4GskU7ybcZQ"
          
          USER_AGENTS=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
          )

          REFS=(
            "https://www.google.com" 
            "https://www.twitter.com" 
            "https://www.reddit.com"
            "https://t.co"
          )

          echo "Starting USA Server Injection for Video: $VIDEO_ID"

          for i in {1..70}
          do
            UA=${USER_AGENTS[$RANDOM % ${#USER_AGENTS[@]}]}
            REF=${REFS[$RANDOM % ${#REFS[@]}]}
            
            # View + Interaction Signal
            curl -A "$UA" -e "$REF" -s -L "https
            
